AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
        nom:
            type: string
            length: '255'
        description:
            type: text
        prix:
            type: float
        stock:
            type: integer

    manyToMany:
        commandes:
            targetEntity: Commande
            inversedBy: article
            cascade: ['all']

    lifecycleCallbacks: {  }
